import unittest

from ordered_list import *


class TestOrderedList(unittest.TestCase):

    def test_delete(self):
        orderedList = OrderedList(True)
        orderedList.delete(5)
        self.assertEqual(orderedList.get_all_values(), [])
        orderedList.add(5)
        orderedList.add(8)
        orderedList.add(6)
        orderedList.add(7)
        orderedList.add(7)
        orderedList.delete(7)
        self.assertEqual(5, orderedList.head.value)
        self.assertEqual(8, orderedList.tail.value)
        self.assertEqual(orderedList.get_all_values(), [5, 6, 7, 8])
        orderedList.delete(5)
        self.assertEqual(6, orderedList.head.value)
        self.assertEqual(8, orderedList.tail.value)
        self.assertEqual(orderedList.get_all_values(), [6, 7, 8])
        orderedList.delete(8)
        self.assertEqual(6, orderedList.head.value)
        self.assertEqual(7, orderedList.tail.value)
        self.assertEqual(orderedList.get_all_values(), [6, 7])
        orderedList.delete(80)
        self.assertEqual(orderedList.get_all_values(), [6, 7])
        orderedList = OrderedList(False)
        orderedList.delete(5)
        self.assertEqual(orderedList.get_all_values(), [])
        orderedList.add(5)
        orderedList.add(8)
        orderedList.add(6)
        orderedList.add(7)
        orderedList.add(7)
        orderedList.delete(7)
        self.assertEqual(8, orderedList.head.value)
        self.assertEqual(5, orderedList.tail.value)
        self.assertEqual(orderedList.get_all_values(), [8, 7, 6, 5])
        orderedList.delete(5)
        self.assertEqual(8, orderedList.head.value)
        self.assertEqual(6, orderedList.tail.value)
        self.assertEqual(orderedList.get_all_values(), [8, 7, 6])
        orderedList.delete(8)
        self.assertEqual(7, orderedList.head.value)
        self.assertEqual(6, orderedList.tail.value)
        self.assertEqual(orderedList.get_all_values(), [7, 6])
        orderedList.delete(80)
        self.assertEqual(orderedList.get_all_values(), [7, 6])


    def test_insert(self):
        orderedList = OrderedList(True)
        orderedList.add(5)
        self.assertEqual(5, orderedList.head.value)
        self.assertEqual(5, orderedList.tail.value)
        self.assertEqual(orderedList.get_all_values(), [5])
        orderedList.add(6)
        self.assertEqual(5, orderedList.head.value)
        self.assertEqual(6, orderedList.tail.value)
        self.assertEqual(orderedList.get_all_values(), [5, 6])
        orderedList.add(7)
        orderedList.add(10)
        orderedList.add(8)
        orderedList.add(10)
        self.assertEqual(5, orderedList.head.value)
        self.assertEqual(10, orderedList.tail.value)
        self.assertEqual(orderedList.get_all_values(), [5, 6, 7, 8, 10, 10])
        orderedList.add(1)
        self.assertEqual(1, orderedList.head.value)
        self.assertEqual(10, orderedList.tail.value)
        self.assertEqual(orderedList.get_all_values(), [1, 5, 6, 7, 8, 10, 10])
        orderedList.add(11)
        self.assertEqual(1, orderedList.head.value)
        self.assertEqual(11, orderedList.tail.value)
        self.assertEqual(orderedList.get_all_values(), [1, 5, 6, 7, 8, 10, 10, 11])
        orderedList = OrderedList(False)
        orderedList.add(5)
        self.assertEqual(5, orderedList.head.value)
        self.assertEqual(5, orderedList.tail.value)
        self.assertEqual(orderedList.get_all_values(), [5])
        orderedList.add(6)
        self.assertEqual(6, orderedList.head.value)
        self.assertEqual(5, orderedList.tail.value)
        self.assertEqual(orderedList.get_all_values(), [6, 5])
        orderedList.add(7)
        orderedList.add(10)
        orderedList.add(8)
        self.assertEqual(10, orderedList.head.value)
        self.assertEqual(5, orderedList.tail.value)
        self.assertEqual(orderedList.get_all_values(), [10, 8, 7, 6, 5])
        orderedList.add(1)
        self.assertEqual(10, orderedList.head.value)
        self.assertEqual(1, orderedList.tail.value)
        self.assertEqual(orderedList.get_all_values(), [10, 8, 7, 6, 5, 1])
        orderedList.add(11)
        self.assertEqual(11, orderedList.head.value)
        self.assertEqual(1, orderedList.tail.value)
        self.assertEqual(orderedList.get_all_values(), [11, 10, 8, 7, 6, 5, 1])

    def test_find(self):
        orderedList = OrderedList(True)
        self.assertEqual(None, orderedList.find(50))
        orderedList.add(67)
        orderedList.add(34)
        orderedList.add(5)
        orderedList.add(67)
        orderedList.add(43)
        self.assertEqual(5, orderedList.find(5).value)
        self.assertEqual(None, orderedList.find(50))


if __name__ == '__main__':
    unittest.main()
